backend/carrinho/urls.py
from django.urls import path

from .views import (
    CarrinhoAdicionarProdutoView,
    CarrinhoAtualizarProdutoView,
    CarrinhoRemoverProdutoView,
    CarrinhoView,
)

app_name = 'carrinho'

urlpatterns = [
    path('', CarrinhoView.as_view(), name='carrinho'),
    path('adicionar-produto',
         CarrinhoAdicionarProdutoView.as_view(),
         name='adicionar_produto'),
    path('atualizar-produto',
         CarrinhoAtualizarProdutoView.as_view(),
         name='atualizar_produto'),
    path('remover-produto',
         CarrinhoRemoverProdutoView.as_view(),
         name='remover_produto'),
]

backend/landing_pages/urls.py
from django.urls import path

from .views import ContateNosView, sobre_nos

app_name = "landing_pages"

urlpatterns = [
    path('sobre-nos/', sobre_nos, name='sobre_nos'),
    path('contate-nos/', ContateNosView.as_view(), name='contate_nos'),
]

backend/pedidos/urls.py
from django.urls import path

from .views import IdentificacaoView, PagamentoView, PedidoDetailView

app_name = 'pedidos'

urlpatterns = [
    path("pedido/<int:pk>/", PedidoDetailView.as_view(), name='pedido_detalhe'),
    path("identificacao/", IdentificacaoView.as_view(), name='identificacao'),
    path("pagamento/", PagamentoView.as_view(), name='pagamento'),
]

backend/produtos/urls.py
from django.urls import path

from .views import (
    CategoriaListView,
    CompraPorCategoriaListView,
    HomeView,
    ProdutoListView,
    SubCategoriaListView,
)

app_name = "produtos"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('compra-por-categoria/',
         CompraPorCategoriaListView.as_view(),
         name='compra_por_categoria'),
    path('categoria/<str:categoria_slug>/',
         CategoriaListView.as_view(),
         name='categoria'),
    path('categoria/<str:categoria_slug>/<str:sub_categoria_slug>/',
         SubCategoriaListView.as_view(),
         name='sub_categoria'),
    path("produtos/", ProdutoListView.as_view(), name='produtos'),
]

backend/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("usuarios.urls")),
    path("", include("produtos.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("carrinho/", include("carrinho.urls")),
    path('', include("landing_pages.urls")),

    path("admin/", admin.site.urls),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/usuarios/urls.py
from django.urls import path

from .views import CadastroView, EsqueceuSenhaView, LoginView, LogoutView, NovaSenhaView

app_name = 'usuarios'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('esqueceu-senha/', EsqueceuSenhaView.as_view(), name='esqueceu_senha'),
    path('nova-senha/<str:uid>/<str:token>/',
         NovaSenhaView.as_view(), name='nova_senha'),
]

backend/templates/partials/_footer.html
{% load static %}
<div class="container">
    <div class="footer__container">
        <div class="footer__logo">
            <img src="{% static 'img/v-mark-vegan-logo-5.png' %}" alt="">
            <p>E-commerces vegano de alimentos oferecem uma ampla variedade de produtos livres de ingredientes de origem
                animal. Essas plataformas são essenciais para consumidores que buscam opções éticas, sustentáveis e
                saudáveis. Com uma seleção diversificada, incluindo alimentos orgânicos e alternativas vegetais para
                produtos tradicionais, esses e-commerces atendem às necessidades dos adeptos do veganismo. Além disso,
                muitos desses e-commerces oferecem recursos educacionais e receitas para apoiar e inspirar uma dieta
                vegana.
            </p>
            <span>vegan@gmail.com | Telefone: 84 93345-3435</span>
        </div>
        <div class="footer__recursos">
            <div class="recursos-titulo">
                <h1>Recursos</h1>
            </div>
            <a href="">Sobre nós</a>
            <a href="">Contato</a>
            <a href="">Perguntas Frequentes</a>
            <a href="">Politica de Envio</a>
            <a href="">Politica de Devolucão</a>
            <a href="">Politica de Privacidade</a>
            <a href="">Solitição de Fornecedor</a>
        </div>
        <div class="footer__prod-popular">
            <div class="prod-titulo">
                <h1>Produtos Popular</h1>
            </div>
            <a href="">Lanches</a>
            <a href="">Alternativas de Queijos</a>
            <a href="">Alternativas de Carnes</a>
            <a href="">Doces</a>
            <a href="">Sucos</a>
        </div>
    </div>
</div><!--Fin da div Container-->

backend/templates/partials/_form.html
{% csrf_token %}
{% if  form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-warning">
          {{error}}
        </div>
      {% endfor %}
{% endif %}

{% for field in form %}
    <label for="{{field.id_for_label}}">{{field.label}}: </label>
    {{field}}
    {{field.help_text}}

    {% if  field.errors %}
        {% for error in field.errors %}
           <div class="from__erro">
            {{error}}
           </div>
        {% endfor %}
    {% endif %}
{% endfor %}

backend/templates/partials/_head.html
{% load static %} 
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!--bootstrap-icons-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<!--Fim bootstrap-icons-->

<!--Fonte do Google-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<!--Fim da Fonte do Google-->

<link rel="shortcut icon" href="{% static 'img/v-mark-vegan-logo-5.png' %}" type="image/x-icon">

<script src="https://code.jquery.com/jquery-3.6.0.min.js" defer></script>

<link rel="stylesheet" href="{% static 'css/main.css'%}">


<script src="{% static 'js/categoria.js' %}" defer></script>
<script src="{% static 'js/sub_categoria.js' %}" defer></script>
<script src="{% static 'js/script.js' %}" defer></script>


<!--============================================================================-->
<!--Estilo do slide da categoria-->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>

<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

<!--============================================================================-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

backend/templates/partials/_header.html
{% load static %}
<div class="container">
    <div class="header__logo">
        <img src="{% static 'img/v-mark-vegan-logo-5.png' %}" alt="">
    </div>

    <nav class="header__navegacao">
        <ul>
            <li><a href="{% url 'produtos:home' %}">Home</a></li>
            <li><a href="{% url 'produtos:compra_por_categoria' %}">Compre Por Categoria</a></li>
            <li><a href="{% url 'landing_pages:sobre_nos' %}">Sobre Nos</a></li>
            <li><a href="{% url 'landing_pages:contate_nos' %}">Contate-nos</a></li>
        </ul>
    </nav>

    <div class="flex">
        <div class="input__pesquisa">
            <form action="{% url 'produtos:produtos' %}" method='GET' >
                <input type="text" placeholder="Pesquise produto, marcas, etc..." name="search" {% if request.GET.search %}value="{{request.GET.search}}"{% endif %} >
                    <button type="submit">
                       <i class="bi bi-search"></i>
                    </button> 
            </form>
    </div>
       <div class="header__icons">
           {% if request.user.is_authenticated %}
           <a href="{% url 'usuarios:logout' %}"><i class="bi bi-box-arrow-right"></i>
           {% else %}
           <a href="{% url 'usuarios:login' %}"><i class="bi bi-person"></i>
           </a>
           {% endif %}
           <a href="{% url 'carrinho:carrinho' %}"><i class="bi bi-cart3"></i>
           </a>
       </div>
    </div>
</div>

backend/templates/partials/adicionar_produto_ao_carrinho.html
<form action="{% url 'carrinho:adicionar_produto' %}" method="POST">{% csrf_token %} 
    {% if produto.imagem %}
    <img src="{{produto.imagem.url}}" alt="">
    {% endif %}
    <p>{{produto.nome}}</p>
    <div class="preco_quantidade">
        <span>R${{produto.preco}}</span>
        <input class="quantidade" type="number" value="0" min="1" max="{{produto.estoque}}" name="quantidade">
    </div>
        <input type="hidden" value="{{produto.id}}" name="produto_id">
        <button type="submit" class="button__adicionar-carrinho">Adicionar no carrinho</button>
</form>

backend/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

backend/templates/partials/pagination.html
{% if is_paginated %}
<div class="row mt-3">
    <div class="col">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if url_filtro_com_paginacao %}{{url_filtro_com_paginacao}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}