backend/carrinho/urls.py
from django.urls import path

from .views import (
    CarrinhoAdicionarProdutoView,
    CarrinhoAtualizarProdutoView,
    CarrinhoRemoverProdutoView,
    CarrinhoView,
)

app_name = 'carrinho'

urlpatterns = [
    path('', CarrinhoView.as_view(), name='carrinho'),
    path('adicionar-produto',
         CarrinhoAdicionarProdutoView.as_view(),
         name='adicionar_produto'),
    path('atualizar-produto',
         CarrinhoAtualizarProdutoView.as_view(),
         name='atualizar_produto'),
    path('remover-produto',
         CarrinhoRemoverProdutoView.as_view(),
         name='remover_produto'),
]

backend/pedidos/urls.py
from django.urls import path

from .views import IdentificacaoView, PagamentoView, PedidoDetailView

app_name = 'pedidos'

urlpatterns = [
    path("pedido/<int:pk>/", PedidoDetailView.as_view(), name='pedido_detalhe'),
    path("identificacao/", IdentificacaoView.as_view(), name='identificacao'),
    path("pagamento/", PagamentoView.as_view(), name='pagamento'),
]

backend/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("usuarios.urls")),
    path("", include("produtos.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("carrinho/", include("carrinho.urls")),
    path('', include("landing_pages.urls")),

    path("admin/", admin.site.urls),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/carrinho/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.manager import Manager

from produtos.models import Produto

user_model = get_user_model()


# Create your models here.

class ManagerCarrinho(Manager):

    def get_or_create(self, user):
        """ Retorna o carrinho do usuário ou cria um novo """
        qs_carrinho = self.get_queryset().filter(user=user, ativado=True)
        if qs_carrinho.exists():
            return qs_carrinho.first()
        return Carrinho.objects.create(user=user)


class Carrinho(models.Model):
    user = models.ForeignKey(user_model, on_delete=models.CASCADE, null=True)
    ativado = models.BooleanField(default=True)

    objects = ManagerCarrinho()

    def __str__(self):
        """ Retorna a representação do objeto como String """
        return f"Carrinho do usuario: {self.user.nome_completo}"

    @property
    def total(self):
        """ Retorna o preço total dos itens do carrinho """
        return sum([item.total for item in self.itens.all()])


class ItemProduto(models.Model):
    carrinho = models.ForeignKey(
        Carrinho, on_delete=models.CASCADE, related_name='itens', null=True)
    produto = models.ForeignKey(
        Produto, on_delete=models.CASCADE, related_name='carrinho_itens')
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Item: {self.produto}, está no {self.carrinho}"

    @property
    def total(self):
        """ Retorna o preço total do produto """
        return self.produto.preco * self.quantidade

backend/carrinho/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from django.utils.decorators import method_decorator
from django.views.generic.base import View

from produtos.models import Produto

from .models import Carrinho, ItemProduto

# Create your views here.


class CarrinhoMixinView(View):
    """
        class mixin define alguns methods que seram herdados por outras views.
    """
    template_name = 'carrinho/carrinho.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            produto_id = request.POST.get("produto_id", None)
            self.produto = get_object_or_404(Produto, id=produto_id)

        self.carrinho = Carrinho.objects.get_or_create(request.user)
        return super().dispatch(request, *args, **kwargs)

    def get_item_carrinho_or_404(
            self, carrinho: Carrinho = None, produto_id=None):
        """
            Tenta pegar o produto que está no carrinho ou lança um Http 404.
        """
        if carrinho and produto_id:
            return get_object_or_404(carrinho.itens.all(),
                                     produto_id=produto_id)
        return get_object_or_404(self.carrinho.itens.all(),
                                 produto_id=self.produto.id)

    def get_quantidade_ou_redirect(self):
        """
            retorna a quantidade e diz se deve redirecionar ou não dependendo
            se a quantidade for válida.
        """
        quantidade = self.request.POST.get("quantidade", None)
        redirecionar = True
        if quantidade is not None:
            try:
                quantidade = int(quantidade)
                if quantidade <= 0:
                    messages.warning(
                        self.request,
                        "A quantidade do produto deve ser maior que Zero")
                else:
                    redirecionar = False
            except ValueError:
                messages.error(
                    self.request,
                    "A quantidade do produto não é um número inteiro"
                )
        else:
            messages.warning(
                self.request, "Quantidade do produto não fornecida")

        return (redirecionar, quantidade)


class CarrinhoView(CarrinhoMixinView):

    def get(self, request, *args, **kwargs):
        itens_deletados = []
        itens_quantidade_alterada = []

        for item in self.carrinho.itens.all():
            # verifica se o produto ainda está disponível
            if item.produto.estoque == 0:
                itens_deletados.append(item.produto.name)
                item.delete()
            # verifica se a quantidade do item está acima do estoque do produto
            elif item.quantidade > item.produto.estoque:
                itens_quantidade_alterada.append(item.produto.name)
                item.quantidade = item.produto.estoque
                item.save()

        if itens_deletados:
            messages.warning(
                request,
                ("Alguns produtos do seu carrinho não estão mais disponíveis:"
                 f"{itens_deletados}")

            )
        if itens_quantidade_alterada:
            messages.warning(
                request,
                ("Alguns produtos do seu carrinho estavam com estoque "
                    "insuficiente então a quantidade desses produtos foram "
                    "ajustadas para a quantidade disponível: "
                    f"{itens_quantidade_alterada}"))

        return render(request, self.template_name, {'carrinho': self.carrinho})


class CarrinhoAtualizarProdutoView(CarrinhoMixinView):

    def post(self, request, *args, **kwargs):
        redirecionar, quantidade = self.get_quantidade_ou_redirect()
        if redirecionar:
            return redirect(request.META.get('HTTP_REFERER'))

        item = self.get_item_carrinho_or_404()
        item.quantidade = quantidade
        item.save()
        messages.success(request, "A quantidade do produto foi atualizada")
        return redirect(reverse('carrinho:carrinho'))


class CarrinhoAdicionarProdutoView(CarrinhoMixinView):

    def post(self, request, *args, **kwargs):
        redirecionar, quantidade = self.get_quantidade_ou_redirect()
        _redirect = redirect(request.META.get('HTTP_REFERER'))
        if redirecionar:
            return _redirect

        try:
            # pegar o item do carrinho em que o produto estive
            item = self.carrinho.itens.get(produto_id=self.produto.id)
            item_quantidade_anterior = item.quantidade
            item.quantidade += quantidade

            # verifica se o produto tem quantidade suficiente para ser
            # adicionado ao carrinho.
            if item.quantidade > item.produto.estoque:
                produto_estoque = item.produto.estoque
                quantidade_adicionada = (
                    produto_estoque - item_quantidade_anterior)

                # é adicionada a quantidade disponível do produto ao item
                item.quantidade = produto_estoque
                item.save()

                mensagem = (f"Há apenas {produto_estoque} unidades do produto,"
                            " Em seu carrinho já haviam "
                            f"{item_quantidade_anterior} unidades")
                if quantidade_adicionada != 0:
                    mensagem += (
                        f'apenas {quantidade_adicionada} foram adicionadas')
                mensagem += '.'

                messages.warning(request, mensagem)
                return _redirect

            item.save()
        except ItemProduto.DoesNotExist:
            # se não existir, cria um novo item
            item = ItemProduto.objects.create(carrinho=self.carrinho,
                                              produto=self.produto,
                                              quantidade=quantidade)

        messages.success(
            request, f"Adicionamos ao carrinho {self.produto}X{quantidade}")
        return _redirect


class CarrinhoRemoverProdutoView(CarrinhoMixinView):

    def post(self, request, *args, **kwargs):
        item = self.get_item_carrinho_or_404()
        item.delete()
        messages.success(
            request, f"Produto {self.produto} Removido do carrinho")
        return redirect(reverse('carrinho:carrinho'))

backend/carrinho/templates/carrinho/carrinho.html
{% extends "base.html" %}
{% load static %}

{% block title %} Veganos Naturais {% endblock title %}

{% block header %}
    <div class="carrinho__container">
        <div class="header__carrinho-container-logo">
            <img src="{% static 'img/logo_header_carrinho.png' %}" alt="">
        </div>
        <div class="borda"></div>
    </div>
{% endblock header %}

{% block content %}

        <section>
            <div class="main__carrinho-container">
            <div class="carrinho-container-icons">
                <div class="icons">
                    <a href="{% url 'carrinho:carrinho' %}" style="color: #569641;">
                        <i class="bi bi-cart-fill"></i>
                        <span>Carrinho</span>
                    </a>
                </div>
                <div class="icons">
                    <a href="{% url 'pedidos:identificacao' %}">
                        <i class="bi bi-person-fill"></i>
                        <span>Identificação</span>
                    </a>
                </div>
                <div class="icons">
                    <a href="{% url 'pedidos:pagamento' %}">
                        <i class="bi bi-credit-card-2-back-fill"></i>
                        <span>Pagamento</span>
                    </a>
                </div>
            </div>
            <div class="titulo__carrinho">
                <h1>Carrinho</h1>
            </div>
            <hr width="630" style="margin: 0 auto;">

                <table class="carrinho__adicionado">
                    <tbody class="tbody">
                        {% for item in carrinho.itens.all %}
                    <tr class="produto-adicionado">
                        <td class="carrinho__conteudo-img">
                            {% if item.produto.imagem %}
                            <img src="{{item.produto.imagem.url}}" alt="">
                            {% endif %}
                            <span class="produto-title">{{item.produto.nome}}</span>
                        </td>
                        <td>
                            <span class="produto-preco">{{item.produto.preco}}</span>
                        </td>
                        <td class="remover__quantidade">
                            <form id="remover_atualizar_form_{{item.id}}" method="POST">{% csrf_token %}
                                <input class="input__quantidade" type="number" value="{{item.quantidade}}" min="1" max="{{item.produto.estoque}}" name="quantidade" >
                                <input type="hidden" value="{{item.produto.id}}" name="produto_id" >
                            </form>
                            <button form="remover_atualizar_form_{{item.id}}" formaction="{% url 'carrinho:remover_produto' %}" type="submit" class="button-remov">Remover</button>
                            <button form="remover_atualizar_form_{{item.id}}" formaction="{% url 'carrinho:atualizar_produto' %}" type="submit" >Atualizar</button>
                        </td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>

            <hr width="630" style="margin: 0 auto;">
            <table class="informações__do__produto">
            <tr>
                    <td class="inf-produto">
                       <p>Outras opções de <strong>Entrega</strong> na proxima etapa</p>
                       <p><strong>Frete para o CEP</strong></p>
                       <input type="text" name="" id="" placeholder="00000-000">
                    </td>
                    <td colspan="3" class="total__geral">
                       <p>Frete Total: </p>
                        <div class="total">
                            <strong>Total: </strong>
                            <span>{{carrinho.total}}</span>
                        </div>
                        <div class="button_total">
                            <a href="{% url 'pedidos:identificacao' %}">Continuar</a>
                        </div>
                    </td>
            </tr>
            </table>
        </section>

{% endblock content %}