backend/carrinho/urls.py
from django.urls import path

from .views import (
    CarrinhoAdicionarProdutoView,
    CarrinhoAtualizarProdutoView,
    CarrinhoRemoverProdutoView,
    CarrinhoView,
)

app_name = 'carrinho'

urlpatterns = [
    path('', CarrinhoView.as_view(), name='carrinho'),
    path('adicionar-produto',
         CarrinhoAdicionarProdutoView.as_view(),
         name='adicionar_produto'),
    path('atualizar-produto',
         CarrinhoAtualizarProdutoView.as_view(),
         name='atualizar_produto'),
    path('remover-produto',
         CarrinhoRemoverProdutoView.as_view(),
         name='remover_produto'),
]

backend/pedidos/urls.py
from django.urls import path

from .views import IdentificacaoView, PagamentoView, PedidoDetailView

app_name = 'pedidos'

urlpatterns = [
    path("pedido/<int:pk>/", PedidoDetailView.as_view(), name='pedido_detalhe'),
    path("identificacao/", IdentificacaoView.as_view(), name='identificacao'),
    path("pagamento/", PagamentoView.as_view(), name='pagamento'),
]

backend/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("usuarios.urls")),
    path("", include("produtos.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("carrinho/", include("carrinho.urls")),
    path('', include("landing_pages.urls")),

    path("admin/", admin.site.urls),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/pedidos/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator
from carrinho.models import Carrinho

from .validators import REGEX_ENDERECO, REGEX_NUMERO_ENDERECO, REGEX_CEP

user_model = get_user_model()

# Create your models here.


class Pedido(models.Model):
    STATUS_PEDIDO_PENDENTE = 'P'
    STATUS_PEDIDO_CANCELADO = 'C'
    STATUS_PEDIDO_FINALIZADO = 'F'

    STATUS = (
        (STATUS_PEDIDO_PENDENTE, 'Pendente'),
        (STATUS_PEDIDO_CANCELADO, 'Cancelado'),
        (STATUS_PEDIDO_FINALIZADO, 'Finalizado'),
    )
    user = models.ForeignKey(user_model, on_delete=models.DO_NOTHING,
                             related_name='pedidos', null=True)
    carrinho = models.OneToOneField(
        Carrinho, on_delete=models.DO_NOTHING, null=True)

    status = models.CharField(
        max_length=1,
        default=STATUS_PEDIDO_PENDENTE,
        choices=STATUS
    )
    data_criacao = models.DateTimeField(auto_now_add=True)

    ESTADO_CHOICES = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )

    cep = models.CharField(max_length=8, default='', validators=[
                           REGEX_CEP, MinLengthValidator(8)])
    estado = models.CharField(max_length=2, choices=ESTADO_CHOICES, default='')
    cidade = models.CharField(
        max_length=50, default='', validators=[REGEX_ENDERECO])
    bairro = models.CharField(
        max_length=50, default='', validators=[REGEX_ENDERECO])
    complemento = models.CharField(
        max_length=20, default='', validators=[REGEX_ENDERECO])
    rua = models.CharField(max_length=50, default='',
                           validators=[REGEX_ENDERECO])
    numero = models.CharField(max_length=10, default='', validators=[
                              REGEX_NUMERO_ENDERECO])

    def __str__(self):
        """ Retorna a representação do objeto como uma string """
        return f'Pedido N°{self.id}'

    def get_absolute_url(self):
        """ Retorna a URL de detalhe para o pedido """
        return reverse("pedidos:pedido_detalhe", kwargs={"pk": self.pk})

    @property
    def total(self):
        """ Retorna o valor total do pedido """
        return sum([
            item.produto.preco * item.quantidade
            for item in self.carrinho.itens.all()
        ])

    @property
    def quantidade(self):
        """ Retorna a quantidade total de itens do pedido """
        return sum([item.quantidade for item in self.carrinho.itens.all()])

backend/pedidos/forms.py
from django import forms
import re
from .models import Pedido


class EnderecoForm(forms.ModelForm):

    class Meta:
        model = Pedido
        fields = ('cep', 'estado', 'cidade', 'bairro', 'complemento', 'rua',
                  'numero')

backend/pedidos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction

# Create your views here.

from carrinho.models import Carrinho

from .models import Pedido
from .forms import EnderecoForm


@method_decorator(decorator=login_required, name="dispatch")
class PedidoDetailView(DetailView):
    template_name = 'pedidos/pedido_detalhe.html'
    model = Pedido


@method_decorator(decorator=login_required, name="dispatch")
class PagamentoView(View):
    template_name = "pedidos/pagamento.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        # implmentar a lógica de pagamento

        user = request.user

        carrinho = Carrinho.objects.get_or_create(request.user)

        # verifica se tem produtos no carrinho
        if not carrinho.itens.exists():
            messages.warning(
                request, "Não a produtos no seu carrinho, adicione primeiro")
            return redirect(reverse("produtos:home"))

        endereco = request.session.get('endereco', None)
        # verifica se o endereço foi prenchido
        if not endereco:
            messages.warning(
                request, 'Não foi possível identificar o endereço, adicione primeiro')
            return redirect(reverse('pedidos:identificacao'))

        # diminui o estoque do produto e verifica se o estoque não é suficiente
        # para realizar o pedido
        for item in carrinho.itens.all():
            item.produto.estoque -= item.quantidade
            if item.produto.estoque < 0:
                return redirect(reverse("carrinho:carrinho"))

        try:
            # caso ocorra algum erro nesse bloco de código as alterções não
            # seram salvas no banco.
            with transaction.atomic():
                # salva as alterações no estoque dos produtos
                for item in carrinho.itens.all():
                    item.produto.save()

                # desativa o carrinho
                carrinho.ativado = False
                carrinho.save()

                # cria o pedido
                pedido = Pedido.objects.create(
                    user=user, carrinho=carrinho, **endereco)

                # limpa os campos de endereço
                del request.session['endereco']

                messages.success(request, 'Pedido realizado com sucesso')
                return redirect(pedido.get_absolute_url())
        except transaction.TransactionManagementError:
            messages.warning(
                request, 'Ouve um problema ao realizar seu pedido')
            return redirect(reverse('carrinho:carrinho'))


@method_decorator(decorator=login_required, name="dispatch")
class IdentificacaoView(View):
    template_name = "pedidos/identificacao.html"
    form_class = EnderecoForm
    success_url = 'pedidos:pagamento'

    def get(self, request, *args, **kwargs):
        if endereco := request.session.get('endereco', {}):
            form = self.form_class(initial=endereco)
        else:
            form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            # salva o endereço para ser utilizado na criação do pedido
            request.session['endereco'] = form.cleaned_data
            messages.success(request, 'Endereço salvo com sucesso')
            return redirect(reverse(self.success_url))

        return render(request, self.template_name, {'form': form})

backend/pedidos/templates/pedidos/identificacao.html
{% extends "base.html" %}
{% load static %}

{% block title %} Identificação {% endblock title %}

{% block header %}
    <div class="carrinho__container">
        <div class="header__carrinho-container-logo">
            <img src="{% static 'img/logo_header_carrinho.png' %}" alt="">
        </div>
        <div class="borda"></div>
    </div>
{% endblock header %}

{% block content %}
    <main>
        <section>
            <div class="main__carrinho-container">
            <div class="carrinho-container-icons">
                <div class="icons">
                    <a href="{% url 'carrinho:carrinho' %}">
                        <i class="bi bi-cart-fill"></i>
                        <span>Carrinho</span>
                    </a>
                </div>
                <div class="icons">
                    <a href="{% url 'pedidos:identificacao' %}" style="color: #569641;">
                        <i class="bi bi-person-fill"></i>
                        <span>Identificação</span>
                    </a>
                </div>
                <div class="icons">
                    <a href="{% url 'pedidos:pagamento' %}">
                        <i class="bi bi-credit-card-2-back-fill"></i>
                        <span>Pagamento</span>
                    </a>
                </div>
            </div>
            <div class="titulo__carrinho">
                <h1>Identificação</h1>
            </div>
            <div class="form__indentificacao-container">
                <form action="{% url 'pedidos:identificacao' %}" method="POST" id="identificacao_form"> {% csrf_token %}
                     <div class="identivicacao">
                        <div class="endereco_numero">
                            <div class="endereco_num">
                            <input class="endereco" type="text" name="rua" id="" placeholder="Endereço" {% if form.rua.value %} value="{{form.rua.value}}" {% endif %} >
                            {% if form.rua.errors %}
                                {% for error in form.rua.errors %}
                                    <div class="from__erro">
                                        {{error}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                           </div>
                        <div>
                            <input class="numero" type="text" name="numero" id="" placeholder="N" {% if form.numero.value %} value="{{form.numero.value}}" {% endif %}>
                          
                            {% if form.numero.errors %}
                            {% for error in form.numero.errors %}
                        
                                <div class="from__erro">
                                    {{error}}
                                </div>
                            {% endfor %}
                        {% endif %}
                        </div>
                        </div>
                    </div>
                    <div class="identivicacao__input">
                        <div class="bairo_complemento">
                            <input type="text" name="bairro" id="" placeholder="Bairro" {% if form.bairro.value %} value="{{form.bairro.value}}" {% endif %}>
                            {% if form.bairro.errors %}
                                {% for error in form.bairro.errors %}
                                    <div class="from__erro">
                                        {{error}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <input type="text" name="complemento" id="" placeholder="Compĺemento" {% if form.complemento.value %} value="{{form.complemento.value}}" {% endif %}>
                            {% if form.complemento.errors %}
                                {% for error in form.complemento.errors %}
                                    <div class="from__erro">
                                        {{error}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>     
                    </div>
                    <div class="identivicacao__input">
                        <div class="cidade_estado_cep">
                            <div>
                                <input type="text" name="cidade" id="" placeholder="Cidade" {% if form.cidade.value %} value="{{form.cidade.value}}" {% endif %}>
                                {% if form.cidade.errors %}
                                    {% for error in form.cidade.errors %}
                                        <div class="from__erro">
                                            {{error}}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div>
                                <select id="estado" name="estado" style="color: #000;" >
                                    <option value="Selecione seu estado" selected disabled >Selecione seu estado</option>
                                    {% for option in form.estado %}
                                        {{option}}
                                    {% endfor %}
                                </select>
                                {% if form.estado.errors %}
                                    {% for error in form.estado.errors %}
                                        <div class="from__erro">
                                            {{error}}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                                <div>
                                <input type="text" name="cep" id="" placeholder="CEP" {% if form.cep.value %} value="{{form.cep.value}}" {% endif %} >
                                {% if form.cep.errors %}
                                    {% for error in form.cep.errors %}
                                        <div class="from__erro">
                                            {{error}}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </form>
                <div class="form__buutton">
                    <button type="submit" form="identificacao_form">Continuar</button>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}

backend/pedidos/templates/pedidos/pagamento.html
{% extends "base.html" %}
{% load static %}

{% block title %} Pagamento {% endblock title %}

{% block header %}
    <div class="carrinho__container">
        <div class="header__carrinho-container-logo">
            <img src="{% static 'img/logo_header_carrinho.png' %}" alt="">
        </div>
        <div class="borda"></div>
    </div>
{% endblock header %}

{% block content %}
<main>
    <section>
        <div class="main__carrinho-container">
        <div class="carrinho-container-icons">
            <div class="icons">
                <a href="{% url 'carrinho:carrinho' %}">
                    <i class="bi bi-cart-fill"></i>
                    <span>Carrinho</span>
                </a>
            </div>
            <div class="icons">
                <a href="{% url 'pedidos:identificacao' %}">
                    <i class="bi bi-person-fill"></i>
                    <span>Identificação</span>
                </a>
            </div>
            <div class="icons">
                <a href="{% url 'pedidos:pagamento' %}" style="color: #569641;">
                    <i class="bi bi-credit-card-2-back-fill"></i>
                    <span>Pagamento</span>
                </a>
            </div>
        </div>
        <div class="titulo__carrinho">
            <h1>Pagamento</h1>
        </div>
          <div class="pagamento__container">
               <div class="menu_cartao-credito">
                <div class="menu_conteudo">
                    <i class="bi bi-check"></i>
                    <span>Cartão de Credito</span>
                </div>
                <div class="cartao__img">
                    <img src="{% static 'img/image.png' %}" alt="">
                    <img src="{% static 'img/image copy.png' %}" alt="">
                    <img src="{% static 'img/image copy 2.png' %}" alt="">
                    <img src="{% static 'img/image copy 3.png' %}" alt="">
                </div>
               </div>
               <form class="menu_form" action="{% url 'pedidos:pagamento' %}" method="POST" id="pagamento_form">
                {% csrf_token %}
                   <input type="text" name="" id="" placeholder="Name Card">                    
                   <input type="text" name="" id="" placeholder="Card Number">
                   <div class="validade__codigo">
                       <input class="Valide_Thru" type="month" id="">
                       <input class="Securite_Code" type="text" name="" id="" placeholder="Securite Code">
                   </div>
               </form>
        </div>
        <button form="pagamento_form" >Finalizar Pedido</button>
    </div>
    </section>
</main>
{% endblock content %}

backend/pedidos/templates/pedidos/pedido_detalhe.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

{% extends "base.html" %}
{% load static %}

{% block title %} Pedido N. {{pedido.pk}} {% endblock title %}

{% block content %}
<section>
<div class="container">
<div class="row mb-5">
    <div class="col-lg">
        <h2 style="margin: 50px auto 20px auto;">Detalhe do pedido</h2>

        <p class="lead">Dados do usuário</p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{pedido.user.nome_completo}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{pedido.user.data_nascimento}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{pedido.user.cpf}}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{pedido.user.email}}</dd>
            <dt class="col-lg-2">Tefone:</dt>
            <dd class="col-lg-4">{{pedido.user.telefone}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{pedido.rua}}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{pedido.numero}}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{pedido.cidade}}</dd>
            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{pedido.complemento}}</dd>
            
            <dt class="col-lg-2">Bairro:</dt>
            <dd class="col-lg-4">{{pedido.bairro}}</dd>
            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{pedido.cep}}</dd>

            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{pedido.get_estado_display}}</dd>
        </dl>
    </div>
</div>


<div class="row">
    <div class="col">
        <h3>Método de pagamento</h3>
        <p>Não implementado</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <h3>Pedido N. {{pedido.id}}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{pedido.id}}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">R$ {{pedido.total}}</div>
            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{pedido.quantidade}}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{pedido.get_status_display}}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr style="margin: 0 auto;">
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>QTD.</th>
                    <th>Unidade</th>
                    <th>Total</th>      
                </tr>

                {% for item in pedido.carrinho.itens.all %}
                <tr>                 
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{{item.produto.imagem.url}}">
                    </td>
                    <td>{{item.produto.nome}}</td>
                    <td>{{item.quantidade}}</td>
                    <td>R$ {{item.produto.preco}}</td>
                    <td>
                        R$ {{item.total}}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>

    </div>
</div>
</div><!--Fim da dive container-->
</section>
{% endblock content %}