backend/pedidos/urls.py
from django.urls import path

from .views import IdentificacaoView, PagamentoView, PedidoDetailView

app_name = 'pedidos'

urlpatterns = [
    path("pedido/<int:pk>/", PedidoDetailView.as_view(), name='pedido_detalhe'),
    path("identificacao/", IdentificacaoView.as_view(), name='identificacao'),
    path("pagamento/", PagamentoView.as_view(), name='pagamento'),
]

backend/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("usuarios.urls")),
    path("", include("produtos.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("carrinho/", include("carrinho.urls")),
    path('', include("landing_pages.urls")),

    path("admin/", admin.site.urls),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/usuarios/urls.py
from django.urls import path

from .views import CadastroView, EsqueceuSenhaView, LoginView, LogoutView, NovaSenhaView

app_name = 'usuarios'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('esqueceu-senha/', EsqueceuSenhaView.as_view(), name='esqueceu_senha'),
    path('nova-senha/<str:uid>/<str:token>/',
         NovaSenhaView.as_view(), name='nova_senha'),
]

backend/usuarios/models.py
import re

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from usuarios.managers import CustomUserManager
from usuarios.validators import (
    PADRA_REGEX_CPF,
    PADRA_REGEX_EMAIL,
    PADRA_REGEX_LETRAS,
    PADRA_REGEX_TELEFONE,
    eh_de_maior,
    eh_valido_cpf,
)

# Create your models here.

# customizado o usuário do django para adicionar mais campos e definir outro
# modo de fazer login


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('endereço de email'),
                              unique=True,
                              validators=[
                                  RegexValidator(re.compile(PADRA_REGEX_EMAIL),
                                                 'Endereço de email inválido')
    ])
    nome_completo = models.CharField(
        _("nome"),
        max_length=100,
        validators=[
            RegexValidator(re.compile(PADRA_REGEX_LETRAS, re.I),
                           'Caracteres inválidos, insira apenas letras')
        ])
    cpf = models.CharField(_("CPF"),
                           max_length=14,
                           unique=True,
                           null=True,
                           validators=[
                               eh_valido_cpf,
                               RegexValidator(
                                   re.compile(PADRA_REGEX_CPF),
                                   'CPF não está no padrão exigido', 'invalid')
    ])
    data_nascimento = models.DateField(null=True,
                                       blank=False,
                                       validators=[eh_de_maior])
    telefone = models.CharField(max_length=20,
                                validators=[
                                    RegexValidator(
                                        re.compile(PADRA_REGEX_TELEFONE),
                                        'Número telefone inválido')
                                ])

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_("active"), default=True)
    is_admin = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_(
            "Designates whether the user can log into this admin site."),
    )

    # Manager personalisado para usar a senha como username
    objects = CustomUserManager()

    # Configurando o email que seja usado pra fazer login no sistema
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    # troquei o campo is_staff por is_admin porém o django usa este campo estão
    # criei esta property.
    @property
    def is_staff(self):
        """ Retorna se o usuário é um administrador """
        return self.is_admin

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        """ Retorna a representação do objeto como String """
        return str(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

backend/usuarios/forms.py
import re
from django import forms
from django.contrib.auth import authenticate, get_user_model

from usuarios.utils import Util
from usuarios.validators import PADRA_REGEX_CPF

user_model = get_user_model()


class LoginForm(forms.Form):
    """ Formulário de login do usuário """

    email = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': "E-mail"}))
    senha = forms.CharField(max_length=255,
                            widget=forms.TextInput(attrs={
                                'type': "password",
                                'placeholder': "Senha"
                            }))

    def usuario_eh_autenticado(self) -> user_model | None:
        """ Retorna o usuário se as credenciais forem válidas"""

        email = self.cleaned_data['email']
        senha = self.cleaned_data['senha']
        #
        user = authenticate(email=email, password=senha)
        return user


class UserForm(forms.ModelForm):
    """ Formulário de cadastro do usuário """

    senha = forms.CharField(max_length=255, min_length=8,
                            widget=forms.TextInput(attrs={
                                'type': "password",
                                'placeholder': "Senha",
                            }))

    class Meta:
        model = user_model
        fields = ("nome_completo", 'cpf', 'data_nascimento', 'telefone',
                  'email', 'senha')
        widgets = {
            'nome_completo': forms.TextInput(
                attrs={'placeholder': "Informe seu nome completo"}),
            'cpf': forms.TextInput(attrs={'placeholder': "000.000.000-00"}),
            'telefone': forms.TextInput(
                attrs={'placeholder': "(DDD) 00000-0000"}),
            'data_nascimento': forms.DateInput(
                attrs={'placeholder': "Informe sua data de nascimento"}),
            'email': forms.EmailInput(
                attrs={'placeholder': "Exemplo@exemplo.com"}),
        }

    def save(self, **kwargs):
        password = self.cleaned_data.pop('senha')
        user = user_model.objects.create_user(
            password=password, **self.cleaned_data)
        return user


class EnviarEmailResetSenhaForm(forms.Form):
    """ Formulário de envio de email para reset de senha """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    email_ou_cpf = forms.CharField(max_length=255, label="E-mail ou cpf",
                                   widget=forms.TextInput(attrs={
                                       'placeholder': "E-mail ou cpf",
                                   }))

    class Meta:
        fields = ('email_ou_cpf', )

    def clean_email_ou_cpf(self):
        email_ou_cpf = self.cleaned_data['email_ou_cpf']
        return email_ou_cpf

    def clean(self):
        cleaned_data = super().clean()
        email_ou_cpf = cleaned_data['email_ou_cpf']
        regex_cpf = re.compile(PADRA_REGEX_CPF)

        if '@' not in email_ou_cpf and not regex_cpf.match(email_ou_cpf):
            raise forms.ValidationError("credencial inválida")

        if user_model.objects.filter(email=email_ou_cpf).exists():
            self.user = user_model.objects.get(email=email_ou_cpf)

        elif user_model.objects.filter(cpf=email_ou_cpf).exists():
            self.user = user_model.objects.get(cpf=email_ou_cpf)

        if self.user is None:
            raise forms.ValidationError('Usuário não registrado no sistema')

        return cleaned_data

    def get_link_reset_password(self):
        return Util.get_link_reset_senha(self.user)


class ChangePasswordSerializer(forms.Form):
    """ Formulário de alteração de senha """

    senha = forms.CharField(
        min_length=8,
        max_length=255, label="Informe a nova senha",
        widget=forms.TextInput(attrs={
            'type': "password",
            'placeholder': "Nova senha",
        })
    )

    senha2 = forms.CharField(
        min_length=8,
        max_length=255, label="Confirme a nova senha",
        widget=forms.TextInput(attrs={
            'type': "password",
            'placeholder': "Confirme a nova senha",
        })
    )

    def clean(self):
        cleaned_data = super().clean()
        senha = cleaned_data['senha']
        senha2 = cleaned_data['senha2']

        if senha != senha2:
            self.add_error(None, 'Senha e confirmar senha devem ser iguais')

        return cleaned_data

backend/usuarios/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.views import View

from usuarios.forms import (
    ChangePasswordSerializer,
    EnviarEmailResetSenhaForm,
    LoginForm,
    UserForm,
)
from usuarios.utils import Util

# Create your views here.


class LoginView(View):
    template_name = 'usuarios/login.html'

    def post(self, request,  *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.usuario_eh_autenticado()
            if user:
                login(request, user)
                next = request.POST.get('next', None)
                if next:
                    return redirect(next)
                return redirect(reverse('produtos:home'))

            messages.error(request, 'Usuário não encontrado')
        return render(request, self.template_name, {'form': form})

    def get(self, request,  *args, **kwargs):
        context = {
            'form': LoginForm(),
            'next': request.GET.get('next', None)
        }
        return render(request, self.template_name, context)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        email = request.user.email
        logout(request)
        messages.success(request, f'Usuário {email} deslogado')
        return redirect(reverse('produtos:home'))


class CadastroView(View):
    template_name = 'usuarios/cadastro.html'

    def post(self, request,  *args, **kwargs):
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('produtos:home'))
        return render(request, self.template_name, {'form': form})

    def get(self, request,  *args, **kwargs):
        return render(request, self.template_name, {'form': UserForm()})


class EsqueceuSenhaView(View):
    template_name = 'usuarios/esqueceu_senha.html'

    def post(self, request,  *args, **kwargs):
        form = EnviarEmailResetSenhaForm(request.POST)
        if form.is_valid():
            link = form.get_link_reset_password()
            Util.send_email_reset_password(form.user, link)
            messages.success(
                request, 'Email enviar acesse o link para redefinir sua senha')
            return redirect(reverse('usuarios:esqueceu_senha'))
        return render(request, self.template_name, {'form': form})

    def get(self, request,  *args, **kwargs):
        context = {'form': EnviarEmailResetSenhaForm()}
        return render(request, self.template_name, context)


class NovaSenhaView(View):
    template_name = 'usuarios/nova_senha.html'

    def get(self, request, uid, token, *args, **kwargs):
        if not Util.eh_valido_uid_token(uid, token):
            raise Http404("Acesso Negado")
        context = {
            'form': ChangePasswordSerializer(),
            'uid': uid,
            'token': token
        }
        return render(request, self.template_name, context)

    def post(self, request, uid, token, *args, **kwargs):
        form = ChangePasswordSerializer(request.POST)
        if form.is_valid():
            user = Util.get_user(uid)
            if not user:
                raise Http404("Acesso Negado")
            user.set_password(form.data['senha'])
            user.save()
            return redirect(reverse('usuarios:login'))
        context = {
            'form': form,
            'uid': uid,
            'token': token
        }
        return render(request, self.template_name, context)

backend/usuarios/templates/usuarios/cadastro.html
{% extends "base.html" %}

{% block title %} Cadastro {% endblock title %}

{% block content %}

<section>
    <div class="cadastre-se">
        <div class="cadastre__se-conteudo">
            <h1>Criar Nova Conta De Cliente</h1>
            <p>Criar uma conta é fácil. Basta preencher o formulário abaixo.</p>
        </div>

        <form action="{% url 'usuarios:cadastro' %}" method="POST">
            {% include 'partials/_form.html' %}
            <div class="button_cadastro">
                <button type="submit">Criar</button>
            </div>
            
        </form>
    </div>
</section>

{% endblock content %}

backend/usuarios/templates/usuarios/esqueceu_senha.html
{% extends "base.html" %}

{% block title %} Esqueceu Senha {% endblock title %}

{% block content %}
<section>
    <div class="esqueceu__senha-container">
        <div class="senha__container-titulo">
            <h1>Esqueceu Senha</h1>
            <p>Para recuperar seu acesso, precisamos do seu E-mail ou CPF.</p>
        </div>

        <form action="{% url 'usuarios:esqueceu_senha' %}" method="POST">
            {% block messages %}{% include 'partials/messages.html' %}{% endblock messages %}
            {% include 'partials/_form.html' %}
            <div class="button__esqueceu-senha">
                <button type="submit"> Continuar </button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

backend/usuarios/templates/usuarios/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock title %}

{% block content %}

<section>
    <div class="login__container">
        <div class="login_conteudo">
            <h1>Clientes Registrados</h1>
            <p>Se você tiver uma conta, faça login com seu endereço de e-mail.</p>
        </div>
        <form action="{% url 'usuarios:login' %}", method='POST'>{% csrf_token %}
            {% block messages %}{% include 'partials/messages.html' %}{% endblock messages %}

            {% for field in form %}
                <label for="{{field.id_for_label}}">{{field.label}}: </label>
                {{field}}
            {% endfor %}
            {% if next %}
                <input type="hidden" value="{{next}}" name="next" >
            {% endif %}
            <input type="submit" class="button_cliente" value="Login" >
            <span><a href="{% url 'usuarios:esqueceu_senha' %}">Esqueseu sua senha?</a></span>
        </form>
    </div>
</section>

<section>
    <div class="novo__cliente">
        <div class="cliente">
            <h1>Novos Clientes</h1>
            <p>
                Criar uma conta traz muitos benefícios: finalizar a compra com mais rapidez, manter mais de um endereço, rastrear pedidos e muito mais.
            </p>
        </div>
        <div class="button_clien">
            <a href="{% url 'usuarios:cadastro' %}">Criar a sua conta aqui</a>
        </div>
    </div>
</section>

{% endblock content %}

backend/usuarios/templates/usuarios/nova_senha.html
{% extends "base.html" %}

{% block title %} Nova Senha {% endblock title %}

{% block content %}
<section>
    <div class="container_novasenha">
        <div class="titulo__novasenha">
            <h1>Criar a Nova Senha</h1>
            <p>Sua senha deve conter no minimo 8 caractere!!!</p>
        </div>
        <form action="{% url 'usuarios:nova_senha' uid token %}" method="POST">
            {% include 'partials/_form.html' %}
            <div class="button__novasenha">
                <button type="submit">Confirmar</button>
            </div>
        </form>
    </div>
</section>

{% endblock content %}